name: azureai
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy==1.14.5
  - scipy==1.1.0
  - ipython==6.4.0
  - pandas==0.23.0
  - jupyter==1.0.0
  - ipykernel==4.8.2
  - scikit-learn==0.19.1
  - pip:
    - tensorflow-gpu==1.8.0
